version: '3'

services:
    emeric-web:
        image: nginx:1.11
        container_name: emeric-web
        working_dir: /var/www
        volumes:
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - ./static:/var/www

    emeric-jekyll:
        image: jekyll/jekyll:latest
        container_name: emeric-jekyll
        working_dir: /srv/jekyll
        volumes:
            - ./:/srv/jekyll
            - ./vendor/bundle:/usr/local/bundle
        command: jekyll build --watch --incremental --force_polling
